### PR TITLE
Implemented the use of the feed parser

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@stulees please review. cheers

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Looks good, I think some cleanup can happen as well though in this PR. 
- The package dependency on `"feedme"` can be removed along with other associated dependencies like `"browserify"`, etc. 
- The gulp tasks can be revised too to remove the unnecessary use of browserify and building a `modules.js`. 
- Remove the import of `modules.js` at https://github.com/Rise-Vision/rise-rss/blob/master/rise-rss.html#L4

**Comment by stulees** [comment]
@rodrigopavezi Forgot to mention also that we should update the README too to reflect these changes, cheers.

**Comment by rodrigopavezi** [comment]
@stulees good points. I will make the changes. cheers

**Comment by rodrigopavezi** [comment]
@stulees changes made. Please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi I think only 1 item in the README example data returned is enough, it's making for a long scroll of example data in the README with 4 items. What do you think?

**Comment by rodrigopavezi** [comment]
@stulees makes sense. Changed. please review. cheers

**Comment by stulees** [comment]
@rodrigopavezi Looks good :+1:

**Pull request merged**
