### PR TITLE
Adding README

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep After you review this PR https://github.com/Rise-Vision/web-component-rise-rss/pull/3, please review this one. Thanks

**Comment by donnapep** [comment]
@stulees I think we should reference `webcomponents.min.js` instead of `webcomponents.js`. Some of the web components' ReadMe files have this already; some don't. When we move to Polymer 1.0, we should actually switch to using the lite version.

Also, I think when you install this component using Bower, it's going to put it in a folder called `web-component-rise-rss` and not one called `rise-rss`. This is another thing I've been updating in the component ReadMes.

If you check the playlist component repo, I added this line to the Run Locally section:

"On Mac, execute the following command in Terminal from one directory level above where the web component resides:"

There is a lot of confusion about having to install dependencies one level up. Have you tried Polyserve out yet and did canonical URLs work with your tests?

**Comment by stulees** [comment]
@donnapep 
- Changed to reference `webcomponents.min.js`
- Corrected folder name that bower will create and install into  `web-component-rise-rss`
- I won't be adding that line you mentioned as I don't have a "Run Locally" section yet. This is because there is no demo file yet, since for the time being, the only way this component works is by using `makeRequest` and therefore it only works within CAP or Viewer (fortunately Widget Preview also works). 
- I did not try Polyserve yet. I initially held off when I saw you log a bug for it, and then also held off since hearing about Polymer 1.0 and our potential upgrade to using it. Also thought it might be worthwhile to check out the new Starter Kit too (https://developers.google.com/web/tools/polymer-starter-kit/)

Can you review again, thanks!

**Comment by donnapep** [comment]
@stulees OK, I'd really like to see what happens when you try Polyserve though in case it's a configuration error on my part. Moving to Polymer 1.0 won't affect this. The starter kit is more for building full-on Polymer apps rather than components. :+1:

**Comment by stulees** [comment]
@donnapep Okay, good to know. I think 'm going to migrate to Polymer 1.0 first and then will give Polyserve a try, thanks.

**Pull request merged**
