### PR TITLE
Infrastructure additions/changes for generated GH documentation

### PR DESCRIPTION
**Pull request by stulees**
- Accounting for repo name in bower and package files
- Moving demo files into new demo/ directory
- Adding necessary `index.html` file for generating GH page
- Adding documentation to `rise-rss.html` for generated GH page
- Modifying README to coincide with GH documentation and restriction of use

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I think we're supposed to be including some standard text in the ReadMe and at the top of the component documentation as per this doc - https://goo.gl/pzfbcy

**Comment by stulees** [comment]
@donnapep Revised the README with our standard first statement

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
